---
aws_region: us-east-1
ecr_repo_url: 533267036595.dkr.ecr.us-east-1.amazonaws.com/ops3-minecraft
image_tag: mc-1.21.1-build1
backup_bucket: cs312-jensjako-ops3-mc-backups
container_name: minecraft
data_dir: /data
